//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTracker.ZipcodeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zipcode", Namespace="http://schemas.datacontract.org/2004/07/ZipcodeService")]
    [System.SerializableAttribute()]
    public partial class Zipcode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipcodeKey {
            get {
                return this.ZipcodeKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeKeyField, value) != true)) {
                    this.ZipcodeKeyField = value;
                    this.RaisePropertyChanged("ZipcodeKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZipcodeServiceReference.IZipcodeService")]
    public interface IZipcodeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipcodeService/QueryZipcode", ReplyAction="http://tempuri.org/IZipcodeService/QueryZipcodeResponse")]
        StaffTracker.ZipcodeServiceReference.Zipcode QueryZipcode(string zipcodeKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipcodeService/InsertZipcode", ReplyAction="http://tempuri.org/IZipcodeService/InsertZipcodeResponse")]
        void InsertZipcode(StaffTracker.ZipcodeServiceReference.Zipcode zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipcodeService/UpdateZipcode", ReplyAction="http://tempuri.org/IZipcodeService/UpdateZipcodeResponse")]
        void UpdateZipcode(string zipcodeKey, StaffTracker.ZipcodeServiceReference.Zipcode zipcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZipcodeService/DeleteZipcode", ReplyAction="http://tempuri.org/IZipcodeService/DeleteZipcodeResponse")]
        void DeleteZipcode(string zipcodeKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZipcodeServiceChannel : StaffTracker.ZipcodeServiceReference.IZipcodeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZipcodeServiceClient : System.ServiceModel.ClientBase<StaffTracker.ZipcodeServiceReference.IZipcodeService>, StaffTracker.ZipcodeServiceReference.IZipcodeService {
        
        public ZipcodeServiceClient() {
        }
        
        public ZipcodeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZipcodeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipcodeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZipcodeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StaffTracker.ZipcodeServiceReference.Zipcode QueryZipcode(string zipcodeKey) {
            return base.Channel.QueryZipcode(zipcodeKey);
        }
        
        public void InsertZipcode(StaffTracker.ZipcodeServiceReference.Zipcode zipcode) {
            base.Channel.InsertZipcode(zipcode);
        }
        
        public void UpdateZipcode(string zipcodeKey, StaffTracker.ZipcodeServiceReference.Zipcode zipcode) {
            base.Channel.UpdateZipcode(zipcodeKey, zipcode);
        }
        
        public void DeleteZipcode(string zipcodeKey) {
            base.Channel.DeleteZipcode(zipcodeKey);
        }
    }
}
