//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTracker.GeolocationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GeolocationServiceReference.IGeolocationService")]
    public interface IGeolocationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeolocationService/GetCountry", ReplyAction="http://tempuri.org/IGeolocationService/GetCountryResponse")]
        string GetCountry(string ipAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeolocationServiceChannel : StaffTracker.GeolocationServiceReference.IGeolocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeolocationServiceClient : System.ServiceModel.ClientBase<StaffTracker.GeolocationServiceReference.IGeolocationService>, StaffTracker.GeolocationServiceReference.IGeolocationService {
        
        public GeolocationServiceClient() {
        }
        
        public GeolocationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeolocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeolocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeolocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCountry(string ipAddress) {
            return base.Channel.GetCountry(ipAddress);
        }
    }
}
